### PR TITLE
Add autogen-modules

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by RyanGlScott** [comment]
Silly question: what _are_ `autogen-modules`?

**Comment by phadej** [comment]
The right way to supress

```
<no location info>: warning: [-Wmissing-home-modules]
    Modules are not listed in command line: Build_doctests
```

but not break `cabal sdist` (it will be broken, if `Cabal` isn't `>= 2.0`, i.e. you aren't using GHC-8.2)

**Comment by phadej** [comment]
`Cabal-2.0` said to me

```
setup: Error: Could not find module: Build_doctests with any suffix:
["gc","chs","hsc","x","y","ly","cpphs","hs","lhs","hsig","lhsig"]. If the
module is autogenerated it should be added to 'autogen-modules'.
```

**Comment by RyanGlScott** [comment]
Ah, OK! I assume that older `Cabal`s will simply not recognize the `autogen-modules` stanza and emit a warning?

**Comment by phadej** [comment]
Yes, except it seems it breaks with GHC-8.0 :/

**Pull request closed without merging**
