### PR TITLE
Fix mbLibraryName with Cabal>=2.5

### PR DESCRIPTION
**Pull request by DanielG**

### CODE REVIEW

**Comment by phadej** [comment]
See discussions in #44  

I'll leave this open until it's time.

**Comment by DanielG** [comment]
Um #44 is this issue, not sure which one you actually mean :)

**Comment by phadej** [comment]
Sorry, #42

**Comment by DanielG** [comment]
Hmm, I would appreciate it if you could merge this anyways. I figured you wouldn't want to release this on Hackage just yet which is why I didn't bother to bump the dependency in the cabal file and fine with me. I just need this in git.

You see I follow Cabal HEAD for cabal-helper and try to update that whenever some breaking change comes along so as to not accumulate too much fixing work over time and cabal-doctest is in my build-plan, so ;)

**Comment by phadej** [comment]
Sorry, I'd like to have `MIN_VERSION_Cabal(2,6,0)` or `MIN_VERSION_Cabal(3,0,0)` whichever it turns out to be. If I merge this, it's something *I* need to remember to change.

**Comment by RyanGlScott** [comment]
This is the reason why I added a [patch in `head.hackage`](https://github.com/hvr/head.hackage/pull/91) for `cabal-doctest` (so that we don't have to keep churning through commits in this repo itself to chase GHC HEAD, a moving target).

**Comment by DanielG** [comment]
I don't really understand why you need that? Whichever version Cabal ends being released as it's certainly going to be >=2.5, so this really only affects people messing with git checkouts, right? What is your concern then?

**Comment by phadej** [comment]
Let's try to resolve this in positive way. As there's clearly some unhappiness with my way to do maintenance. @DanielG want to become a co-maintainer of `cabal-doctest` and do the release duties (looks like revisions won't be enough) for GHC-8.8 (and GHC-8.10), this shouldn't require much of your time, but will help me and Ryan.

In return, you can track `Cabal` `master` in `cabal-doctest` master; if you wish so. You can make or keep refusing to intermediate releases for `GHC HEAD`, as far as https://matrix.hackage.haskell.org/#/package/cabal-doctest stays fully green at all times; and neither Ryan (as acme-kmett co-maintainer) neither myself (as a maintainer of `servant` and related libs which use `cabal-doctest`) don't need to worry about this repository.

(And I have no idea why travis is red, previous build from `master` was green: https://travis-ci.org/phadej/cabal-doctest/branches - maybe something changed in how `cabal-install-2.4` does stuff? that needs to be figured out too).

**Comment by DanielG** [comment]
On Sat, Feb 09, 2019 at 11:09:40AM -0800, Oleg Grenrus wrote:
> Let's try to resolve this in positive way. As there's clearly some
> unhappiness with my way to do maintenance.

I'm not sure how you got that idea, I was really just trying understand what
your maintanance process is and why tracking ghc HEAD doesn't fit in it. It
sounds like you just don't want to waste time merging the related PRs and
that's fair.

> Do you, @DanielG want to become a co-maintainer of `cabal-doctest` and do
> the release duties (looks like revisions won't be enough) for GHC-8.8 (and
> GHC-8.10), this shouldn't require much of your time, but will help me and
> Ryan.
>
> (And I have no idea why travis is red, previous build from `master` was
> green: https://travis-ci.org/phadej/cabal-doctest/branches - maybe
> something changed in how `cabal-install-2.4` does stuff? that needs to be
> figured out too).

I suppose, time allowing, I could do that. The only problem I see is
Travis. I don't really like it much because there is no easy way to run
builds locally for investigating problems -- unless there something to that
these days?

Otherwise would you mind me switching to something else?

**Comment by quasicomputational** [comment]
We're at 8.8.1-alpha2 now; is it time to think about merging this?

There's a (new since this PR?) function, `Distribution.Types.LibraryName.libraryNameString` that  makes implementation a little simpler:

```
@@ -92,6 +92,10 @@ import Distribution.Types.MungedPackageId
        (MungedPackageId)
 import Distribution.Types.UnqualComponentName
        (unUnqualComponentName)
+#if MIN_VERSION_Cabal(3,0,0)
+import Distribution.Types.LibraryName
+       (libraryNameString)
+#endif
 
 -- For amendGPD
 import Distribution.Types.GenericPackageDescription
@@ -429,7 +433,10 @@ generateBuildModule testSuiteName flags pkg lbi = do
        isSpecific _                     = False
 
     mbLibraryName :: Library -> Name
-#if MIN_VERSION_Cabal(2,0,0)
+#if MIN_VERSION_Cabal(3,0,0)
+    -- Types changed around in Cabal-3.0.
+    mbLibraryName = NameLib . fmap unUnqualComponentName . libraryNameString . libName
+#elif MIN_VERSION_Cabal(2,0,0)
     -- Cabal-2.0 introduced internal libraries, which are named.
     mbLibraryName = NameLib . fmap unUnqualComponentName . libName
 #else
```

**Comment by phadej** [comment]
Superseded by https://github.com/phadej/cabal-doctest/pull/52

**Pull request closed without merging**
