### PR TITLE
Autogen modules hook

### PR DESCRIPTION
**Pull request by phadej**
This is fugly :/

### CODE REVIEW

**Comment by RyanGlScott** [comment]
I think this change looks OK, but a comment explaining why this is necessary might be helpful. AFAICT, this is needed because of a mysterious bug in older versions of GHC, right?

**Comment by phadej** [comment]
Especially I don't like I have to discover `*.cabal` file manually.

**Comment by RyanGlScott** [comment]
Another solution would be to simply advise anyone who uses `cabal-doctest` to put `Build_doctests` in the `other-modules` stanza of their `.cabal` file, right? If this solution is too cumbersome, I'd be fine with documenting this advice as an alternative.

**Comment by phadej** [comment]
@RyanGlScott we cannot put it just in `other-modules`, then `cabal sdist` will fail.

**Comment by RyanGlScott** [comment]
Wow, this _is_ fugly.

Well, yet another alternative is: just deal with the warnings. It sucks, but maybe it's an unavoidable part of life until we put a proper solution directly into `cabal-install`. (We could also warn folks to brace themselves for `-Wmissing-home-modules` warnings in the `README`.)

**Comment by phadej** [comment]
Ah, `-Wmissing-home-modules` will make `stack build --pedantic` unhappy...

**Comment by phadej** [comment]
See #30

**Pull request closed without merging**
